# Generated by Django 4.2.11 on 2024-03-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tagging", "0003_adapt_max_tag_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="taggeditem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
